DjanagoProjects/mysite/elections/urls.py
from django.conf.urls import url
from . import views

app_name = 'elections'
urlpatterns = [
   url(r'^$', views.index, name = 'home'),
   url(r'^areas/(?P<area>[가-힣]+)/$', views.areas),
   url(r'^areas/(?P<area>[가-힣].+)/results$', views.results),
   url(r'^polls/(?P<poll_id>\d+)/$', views.polls),
   url(r'^candidates/(?P<name>[가-힝]+)/$', views.candidates),
]

DjanagoProjects/mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('elections.urls')),
    url(r'^admin/', admin.site.urls),
]

DjanagoProjects/mysite/elections/models.py
from django.db import models

# Create your models here.
class Candidate(models.Model):
	name = models.CharField(max_length=10)
	introduction = models.TextField()
	area = models.CharField(max_length=15)
	party_number = models.IntegerField(default=1)

	def __str__(self):
		return self.name

class Poll(models.Model):
	start_date = models.DateTimeField()
	end_date = models.DateTimeField()
	area = models.CharField(max_length=15)

class Choice(models.Model):
	poll = models.ForeignKey(Poll)
	candidate = models.ForeignKey(Candidate)
	votes = models.IntegerField(default=0)
	

DjanagoProjects/mysite/elections/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound, Http404

from .models import Candidate, Poll, Choice

import datetime

from django.db.models import Sum

# Version_0.1
# Create your views here.
# def index(request):
# 	candidates = Candidate.objects.all()
# 	str = ''
# 	for candidate in candidates:
# 		str += "<p>{} 기호 {}번( {} )<br>".format(candidate.name, 
# 			candidate.party_number, 
# 			candidate.area)
# 		str += candidate.introduction + "</p>"
# 	return HttpResponse(str)

# Version_0.2
# def index(request):
# 	candidates = Candidate.objects.all()
# 	return render(request, 'elections/index.html')

# Version_0.3
def index(request):
	print("index start")
	candidates = Candidate.objects.all()
	context = {'candidates': candidates}
	return render(request, 'elections/index.html', context)

# Version_0.1
# def candidates(request, name):
# 	try:
# 		candidate = Candidate.objects.get(name = name)
# 	except:
# 		return HttpResponseNotFound("없는 페이지 입니다.")
# 	return HttpResponse(candidate.name)

# Version_0.2
# def candidates(request, name):
# 	try:
# 		candidate = Candidate.objects.get(name = name)
# 	except:
# 		raise Http404
# 	return HttpResponse(candidate.name)

def candidates(request, name):
	candidate = get_object_or_404(Candidate, name = name)

	return HttpResponse(candidate.name)


# Version_0.1
# def areas(request, area):
	# return HttpResponse(area)

# Version_0.2
# def areas(request, area):
# 	candidates = Candidate.objects.filter(area = area)
# 	context = {
# 		'candidates': candidates,
# 		'area': area
# 	}
# 	return render(request, 'elections/area.html', context)

# Version_0.3
# def areas(request, area):
# 	today = datetime.datetime.now()
# 	poll = Poll.objects.get(area = area, start_date__lte=today, end_date__gte=today)
# 	candidates = Candidate.objects.filter(area = area)
# 	context = {
# 		'candidates': candidates,
# 		'area': area,
# 		'poll': poll
# 	}
	# return render(request, 'elections/area.html', context)

def areas(request, area):
	today = datetime.datetime.now()
	try:
		print("before poll {}", area)
		poll = Poll.objects.get(area = area, start_date__lte=today, end_date__gte=today)
		print("poll", poll)

		candidates = Candidate.objects.filter(area = area)
	except:
		print("---------------------except")
		poll = None
		candidates = None
	context = {
		'candidates': candidates,
		'area': area,
		'poll': poll
	}
	return render(request, 'elections/area.html', context)

# Version_0.1
# def polls(request, poll_id):
# 	poll = Poll.objects.get(pk = poll_id)
# 	selection = request.POST['choice']

# 	try:
# 		choice = Choice.objects.get(poll_id = poll_id, candidate_id = selection)
# 		choice.votes += 1
# 		choice.save()
# 	except:
# 		choice = Choice(poll_id = poll_id, candidate_id = selection, votes=1)
# 		choice.save()

# 	return HttpResponse("finish")

def polls(request, poll_id):
	poll = Poll.objects.get(pk = poll_id)
	selection = request.POST['choice']

	try:
		choice = Choice.objects.get(poll_id = poll_id, candidate_id = selection)
		choice.votes += 1
		choice.save()
	except:
		choice = Choice(poll_id = poll_id, candidate_id = selection, votes=1)
		choice.save()

	return HttpResponseRedirect("/areas/{}/results".format(poll.area))

def results(request, area):
	candidates = Candidate.objects.filter(area = area)
	polls = Poll.objects.filter(area = area)
	poll_results = []
	for poll in polls:
		result = {}
		result['start_date'] = poll.start_date
		result['end_date'] = poll.end_date

		# total_votest가 숫자가 아닌,  dictionary(=json) 형태로 넘겨준다.
		total_votes = Choice.objects.filter(poll_id=poll.id).aggregate(Sum('votes'))
		print("#############", total_votes)

		# 아래 처럼 aggreate된 dictionary에서  key값으로 가져와야 된다.
		result['total_votes'] = total_votes['votes__sum']
		rates = []
		for candidate in candidates:
			try:
				choice = Choice.objects.get(poll_id = poll.id,  candidate_id = candidate.id)
				rates.append( 
					round(choice.votes * 100/result['total_votes'] , 1))
			except:
				rates.append(0)
		result['rates'] = rates

		poll_results.append(result)
	context = {'candidates':candidates, 'area': area, 'poll_results': poll_results}
	return render(request, 'elections/result.html', context)

DjanagoProjects/mysite/elections/templates/elections/History/area_v1.html
<!-- \mysite\templates\elections\area.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <title>지역구</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
<h1>지역구</h1>
<br>
	<table class="table table-striped">
		<thead>
		<tr>
			<td><B>이름</B></td>
			<td><B>소개</B></td>
			<td><B>기호</B></td>
			<td><B>지지하기</B></td>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td> 후보1</td>
			<td> 후보소개 </td>
			<td> 기호1번 </td>
			<td>
				<form action = "#" method="post">
					<button name="choice" value="#">선택</button>
				</form>
			</td>
		</tr>
		<tr>
			<td> 후보2</td>
			<td> 후보소개 </td>
			<td> 기호2번 </td>
			<td>
				<form action = "#" method="post">
					<button name="choice" value="#">선택</button>
				</form>
			</td>
		</tr>       
		</tbody>
	</table>
</div>
</body>

DjanagoProjects/mysite/elections/templates/elections/History/area_v2.html
<!-- \mysite\templates\elections\area.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{{area}}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
<h1>{{area}}</h1>
<br>
	{% if poll %}
	<table class="table table-striped">
		<thead>
		<tr>
			<td><B>이름</B></td>
			<td><B>소개</B></td>
			<td><B>기호</B></td>
			<td><B>지지하기</B></td>
		</tr>
		</thead>
		<tbody>
		{% for candidate in candidates %}
		<tr>
			<td> {{candidate.name}}</td>
			<td> {{candidate.introduction}} </td>
			<td> {{candidate.party_number}}번</td>
			<td>
				<form action = "/polls/{{poll.id}}/" method="post">
				{% csrf_token %}
					<button name="choice" value="{{candidate.id}}">선택</button>
				</form>
			</td>
		</tr>
		{% endfor %}
		</tbody>
	</table>
	{% else %}
	여론조사가 없습니다.
	{% endif %}
</div>
</body>

DjanagoProjects/mysite/elections/templates/elections/History/index_v1.html
<!-- C\Code\mysite\elections\templates\elections\index.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <title>선거 후보</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
</head>
<body>
<div class="container">
    <table class="table table-striped">
        <thead>
        <tr>
            <td><B>이름</B></td>
            <td><B>소개</B></td>
            <td><B>출마지역</B></td>
            <td><B>기호</B></td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>가후보</td>
            <td>후보입니다.</td>
            <td>우리나라</td>
            <td>기호1번</td>
        </tr>
        <tr>
            <td>나후보</td>
            <td>후보입니다.</td>
            <td>우리나라</td>
            <td>기호2번</td>
        </tr>
        <tbody>
    </table>
</body>

DjanagoProjects/mysite/elections/templates/elections/History/index_v2.html
<!-- C\Code\mysite\elections\templates\elections\index.html -->
<!DOCTYPE html>
<html lang="en">
<head>
	<title>선거 후보</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
</head>
<body>
<div class="container">
	<table class="table table-striped">
		<thead>
		<tr>
			<td><B>이름</B></td>
			<td><B>소개</B></td>
			<td><B>출마지역</B></td>
			<td><B>기호</B></td>
		</tr>
		</thead>
		<tbody>
		{% for candidate in candidates %}
		<tr>
			<td>{{candidate.name}}</td>
			<td>{{candidate.introduction}}</td>
			<td>{{candidate.area}}</td>
			<td>{{candidate.party_number}}</td>
		</tr>
		{% endfor %}
		<tbody>
	</table>
</body>

DjanagoProjects/mysite/elections/templates/elections/History/index_v3.html
<!-- C\Code\mysite\elections\templates\elections\index.html -->
<!DOCTYPE html>
<html lang="en">
<head>
	<title>선거 후보</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
</head>
<body>
<div class="container">
	<table class="table table-striped">
		<thead>
		<tr>
			<td><B>이름</B></td>
			<td><B>소개</B></td>
			<td><B>출마지역</B></td>
			<td><B>기호</B></td>
		</tr>
		</thead>
		<tbody>
		{% for candidate in candidates %}
		<tr>
			<td>{{candidate.name}}</td>
			<td>{{candidate.introduction}}</td>
			<td>
				<a href= "areas/{{candidate.area}}/">{{candidate.area}}</a>
			</td>
			<td>{{candidate.party_number}}</td>
		</tr>
		{% endfor %}
		<tbody>
	</table>
</body>

DjanagoProjects/mysite/elections/templates/elections/History/layout_v1.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title %}{% endblock %}</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

DjanagoProjects/mysite/elections/templates/elections/History/result_v1.html
<!-- C:\Code\mysite\elections\templates\elections\result.html -->
<!DOCTYPE html>
<html lang="en">

<head>
    <title>지역구 여론조사 결과</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body>
    <div class="container">
        <h1>지역구</h1>
        <br>
        <table class="table table-striped">
            <thead>
                <tr>
                    <td>
                        <B>기간</B>
                    </td>
                    <td>
                        <B>후보1</B>
                    </td>
                    <td>
                        <B>후보2</B>
                    </td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td> 기간1 </td>
                    <td> 후보1 지지율</td>
                    <td> 후보2 지지율</td>
                </tr>
                <tbody>
        </table>
    </div>
</body>

DjanagoProjects/mysite/elections/templates/elections/History/result_v2.html
<!-- C:\Code\mysite\elections\templates\elections\result.html -->
<!DOCTYPE html>
<html lang="en">

<head>
	<title>{{area}} 여론조사 결과</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body>
	<div class="container">
		<h1>{{area}} 여론조사 결과</h1>
		<br>
		<table class="table table-striped">
			<thead>
				<tr>
					<td><B>기간</B> </td>
					{% for candidate in candidates %}
					<td><B>{{candidate.name}}</B></td>
					{% endfor %}
				</tr>
			</thead>
			<tbody>
				{% for result in poll_results %}
				<tr>
					<td> 
						{{result.start_date.year}}/{{result.start_date.month}}/{{result.start_date.day}} ~ {{result.end_date.year}}/{{result.end_date.month}}/{{result.end_date.day}}
					</td>
					<td> 후보1 지지율</td>
					<td> 후보2 지지율</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</body>

DjanagoProjects/mysite/elections/templates/elections/History/result_v3.html
<!-- C:\Code\mysite\elections\templates\elections\result.html -->
<!DOCTYPE html>
<html lang="en">

<head>
	<title>{{area}} 여론조사 결과</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body>
	<div class="container">
		<h1>{{area}} 여론조사 결과</h1>
		<br>
		<table class="table table-striped">
			<thead>
				<tr>
					<td><B>기간</B> </td>
					{% for candidate in candidates %}
					<td><B>{{candidate.name}}</B></td>
					{% endfor %}
				</tr>
			</thead>
			<tbody>
				{% for result in poll_results %}
				<tr>
					<td> 
						{{result.start_date.year}}/{{result.start_date.month}}/{{result.start_date.day}} ~ {{result.end_date.year}}/{{result.end_date.month}}/{{result.end_date.day}}
					</td>
					{% for rate in result.rates %}
					<td> {{rate}}%</td>
					{% endfor %}
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</body>

DjanagoProjects/mysite/elections/templates/elections/area.html
{% extends "elections/layout.html" %}
{% block title %}
{{area}}
{% endblock %}

{% block content %}
<div class="container">
<h1>{{area}}</h1>
<br>
	{% if poll %}
	<table class="table table-striped">
		<thead>
		<tr>
			<td><B>이름</B></td>
			<td><B>소개</B></td>
			<td><B>기호</B></td>
			<td><B>지지하기</B></td>
		</tr>
		</thead>
		<tbody>
		{% for candidate in candidates %}
		<tr>
			<td> {{candidate.name}}</td>
			<td> {{candidate.introduction}} </td>
			<td> {{candidate.party_number}}번</td>
			<td>
				<form action = "/polls/{{poll.id}}/" method="post">
				{% csrf_token %}
					<button name="choice" value="{{candidate.id}}">선택</button>
				</form>
			</td>
		</tr>
		{% endfor %}
		</tbody>
	</table>
	{% else %}
	여론조사가 없습니다.
	{% endif %}
</div>
{% endblock %}

DjanagoProjects/mysite/elections/templates/elections/index.html
{% extends "elections/layout.html" %}
{% block title %}
선거 후보
{% endblock %}

{% block content %}
<div class="container">
	<table class="table table-striped">
		<thead>
		<tr>
			<td><B>이름</B></td>
			<td><B>소개</B></td>
			<td><B>출마지역</B></td>
			<td><B>기호</B></td>
		</tr>
		</thead>
		<tbody>
		{% for candidate in candidates %}
		<tr>
			<td>{{candidate.name}}</td>
			<td>{{candidate.introduction}}</td>
			<td>
				<a href= "areas/{{candidate.area}}/">{{candidate.area}}</a>
			</td>
			<td>{{candidate.party_number}}</td>
		</tr>
		{% endfor %}
		<tbody>
	</table>
{% endblock %}

DjanagoProjects/mysite/elections/templates/elections/layout.html
<!-- {% load static %} -->
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
	<!-- <link rel="stylesheet" type="text/css" href="{% static 'elections/style.css' %}" /> -->
	<title>{% block title %}{% endblock %}</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	
	<!-- <link rel="icon" type="image/x-icon" href="https://www.w3schools.com/images/w3schools_green.jpg" sizes="16x16"/> -->
	<link rel="icon" type="image/x-icon" href="{% static 'elections/favicon.ico' %}" sizes="16x16"/>
	<!-- <link rel="icon" href="{% static 'elections/favicon.ico' %}" type="image/gif" sizes="16x16"> -->
        <!-- <link rel ="shortcut icon" type = "image/x-icon" href="{% static 'elections/favicon.ico' %}" /> -->
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url  'elections:home' %}">장고를 이용한 투표 사이트</a>
    </div>
</nav>
<img src="{% static 'elections/favicon.ico' %}" alt="Smiley face" height="42" width="42">
{% block content %}{% endblock %}
</body>
</html>

DjanagoProjects/mysite/elections/templates/elections/result.html
{% extends "elections/layout.html" %}
{% block title %}
{{area}} 여론조사 결과
{% endblock %}

{% block content %}
	<div class="container">
		<h1>{{area}} 여론조사 결과</h1>
		<br>
		<table class="table table-striped">
			<thead>
				<tr>
					<td><B>기간</B> </td>
					{% for candidate in candidates %}
					<td><B>{{candidate.name}}</B></td>
					{% endfor %}
				</tr>
			</thead>
			<tbody>
				{% for result in poll_results %}
				<tr>
					<td> 
						{{result.start_date.year}}/{{result.start_date.month}}/{{result.start_date.day}} ~ {{result.end_date.year}}/{{result.end_date.month}}/{{result.end_date.day}}
					</td>
					{% for rate in result.rates %}
					<td> {{rate}}%</td>
					{% endfor %}
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</body>
{% endblock %}